# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
